# Settings.ini
# The file contains the path to monitor and the names of the files to check.
# Each line starting with # is considered a comment and ignored, as are empty lines.
# The correct format for lines is
#
# KEY=value  # comment
#
# where the key name is not case sensitive, while the value is (depending on its use). Comments can only be inserted after the # character,
# any other character will be considered part of the value.
# Any spaces to the right and left of both the key and the value will be ignored.
# For value arrays, the syntax is
#
# *ARRAYNAME = value
#
# where each line containing ARRAYNAME will contain a single value of the array.
# The same rules for single keys apply to names and values.
#
# Notes on parameter types other than strings:
# - the only natively supported numeric types are integers
# - boolean values can be expressed as TRUE / FALSE or 1 / 0 (literal values are not case sensitive)
# - for DayOfWeek values, days must be indicated as a single string containing the corresponding numbers separated by a space, so to
#   indicate Monday, Wednesday, and Friday you must pass the string 1 3 5
#   The values for the days are as follows:
#   0 - Sunday
#   1 - Monday
#   2 - Tuesday
#   3 - Wednesday
#   4 - Thursday
#   5 - Friday
#   6 - Saturday
#
# The INI file can contain the following Pragma values.
# For these to be considered valid, they must be the first valid lines in the file, one per line
# !!SHOWKEYVALUE!!    Enables logging of keys read from the ini file
# !!DEBUG!!           Enables DEBUG log level before the ini file is fully read and ignores any LogLevel value set later.
#                     If the !!PROTOCOL!! pragma is also present, it will take precedence
# !!PROTOCOL!!        Enables PROTOCOL log level before the ini file is fully read and ignores any LogLevel value set later.

KEY1 = {VALUE1}

# Ignored comment

KEY2 = {VALUE2}

KEY3 = {VALUE3}

# Array example

*ARR1 = {ARR1}
*ARR2 = {ARR2}

# Indicates the log level
# 0 - None
# 1 - Error
# 2 - Warning
# 3 - Info
# 4 - Debug
# 5 - Protocol
Loglevel = 4
