# Settings.ini
# Il file contiene il percorso da monitorare e i nomi dei file da verificare.
# Ciascuna riga che inizi con # è considerata un commento ed ignorata, così come le righe vuote.
# Il formato corretto per le righe è 
# 
# CHIAVE=valore  # commento 
# 
# dove il nome della chiave non è case sensitive, mentre il valore lo è (a seconda dell'utilizzo dello stesso). I commenti possono essere inseriti esclusivamente dopo il carattere #,
# qualsiasi altro carattere sarà considerato facente parte del valore.
# Eventuali spazi a destra e sinistra sia della chiave che del valore saranno ignorati
# Per gli array di valori la sintassi è
# 
# *NOMEARRAY = valore
# 
# dove ogni riga contenente NOMEARRAY  conterrà un singolo valore dell'array.
# Per nomi e valori valgono le stesse regole delle chiavi singole.
#
# Note su tipi di parametro differenti dalle stringhe:
# - i tipi numerici supportati nativamente sono esclusivamente gli interi
# - i valori booleani possono essere espressi come TRUE / FALSE o 1 / 0 (i valori letterali non sono case sensitive)
# - per i valori di tipo DayOfWeek I giorni devono essere indicati come una unica stringa contenente i numeri relativi separati da uno spazio, quindi per 
#   indicare il lunedi, il mercoledì ed il venerdì sarà necessario passare la stringa 1 3 5
#   I valori relativi ai giorni sono i seguenti:
#   0 - Domenica
#   1 - lunedi
#   2 - Martedi
#   3 - Mercoledi
#   4 - Giovedì
#   5 - venerdì
#   6 - Sabato
#
# Il file INI può contenere i seguenti valori Pragma.
# Perché questi siano considerati validi devono essere le prime righe valide all'interno del file, uno per ciascuna riga
# !!SHOWKEYVALUE!!    Abilita il logging delle chiavi lette dal file ini
# !!DEBUG!!           Abilita il livello di log DEBUG prima della lettura completa del file ini e ignora l'eventuale valore di LogLevel impostato successivamente. 
#                     Se fosse presente anche la pragma !!PROTOCOL!! questa avrà priorità
# !!PROTOCOL!!        Abilita il livello di log PROTOCOL prima della lettura completa del file ini e ignora l'eventuale valore di LogLevel impostato successivamente. 

KEY1 = {VALUE1}

# Commento ignorato

KEY2 = {VALUE2}

KEY3 = {VALUE3}

# Esempio di array

*ARR1 = {ARR1}
*ARR2 = {ARR2}

# Indica il livello di log
# 0 - None
# 1 - Error
# 2 - Warning
# 3 - Info
# 4 - Debug
# 5 - Protocollo
Loglevel = 4
