using OSKHelpers.Common;
using System;
using System.Linq;
using System.Text;

namespace OSKHelpers.Security
{
    /// <summary>
    /// Class containing methods to keep a password obfuscated in memory.
    /// </summary>
    public class PasswordObfuscator
    {
        #region Constants

        /// <summary>
        /// Length of the seed used for obfuscation.
        /// </summary>
        private const int SEEDLENGTH = 1024;

        #endregion

        #region Members

        /// <summary>
        /// Seed used for password obfuscation.
        /// </summary>
        private static byte[] _seed;
        /// <summary>
        /// Value added to the actual start position of the password<br/>
        /// within <see cref="_seed"/> when storing it in the hash.
        /// </summary>
        private static int _startIndexSeed;

        private static Random _rnd;

        #endregion

        #region Constructor

        static PasswordObfuscator()
        {
            _rnd = new Random();
            ReSeed();
        }

        #endregion

        #region Methods

        /// <summary>
        /// Returns the obfuscated password.
        /// </summary>
        /// <param name="password">Password to obfuscate.</param>
        /// <returns>The obfuscated string containing the password.</returns>
        public static string EncodePassword(string password)
        {
            if (string.IsNullOrWhiteSpace(password))
            {
                throw new ArgumentException($"{nameof(password)} must be a valid string.");
            }

            // choose a random start position
            int startIndex = _rnd.Next(int.MaxValue);

            byte[] pwdBytes = Encoding.UTF8.GetBytes(password);

            byte[] encoded = new byte[pwdBytes.Length];

            for (int i = 0; i < pwdBytes.Length; i++)
            {
                // XOR with the seed, starting from startIndex
                encoded[i] = (byte)(pwdBytes[i] ^ _seed[(startIndex + i) % SEEDLENGTH]);
            }

            // Convert to Base64 for a readable representation
            string encodedBase64 = Convert.ToBase64String(encoded);
            encodedBase64 += EncodeIndex(startIndex);

            return encodedBase64;
        }

        /// <summary>
        /// Returns the plain-text password for the given obfuscated string.
        /// </summary>
        /// <param name="encoded">The obfuscated string generated by <see cref="EncodePassword(string)"/></param>
        /// <returns>The plain-text password.</returns>
        public static string DecodePassword(string encoded)
        {
            // The string to de-obfuscate must be at least 8 characters long (4 are used for
            // encoding the password start index within the hash; a Base64 conversion
            // of a single character occupies 4 bytes and therefore 4 characters).
            if (string.IsNullOrWhiteSpace(encoded) || encoded.Length < 8)
            {
                throw new ArgumentException($"{nameof(encoded)} is not a potentially valid obfuscated string.");
            }

            // Extract the last four characters as the start index for decoding the password.
            // The value is the actual index plus _startIndexSeed, so a subtraction is needed
            // to obtain the correct start index.
            string startChars = encoded.Substring(encoded.Length - 4);
            int startIndex = DecodeIndex(startChars);

            string base64Part = encoded.Substring(0, encoded.Length - 4);
            byte[] encodedBytes = Convert.FromBase64String(base64Part);

            byte[] decoded = new byte[encodedBytes.Length];

            for (int i = 0; i < encodedBytes.Length; i++)
            {
                decoded[i] = (byte)(encodedBytes[i] ^ (_seed[(startIndex + i) % SEEDLENGTH]));
            }

            return Encoding.UTF8.GetString(decoded);
        }

        /// <summary>
        /// Regenerates the seed used for password obfuscation;<br/>
        /// calling this method will invalidate all currently stored passwords.
        /// </summary>
        public static void ReSeed()
        {
            _seed = StringUtils.GenerateAlphaNumericString(SEEDLENGTH).Select(c => (byte)c).ToArray();

            var oldIndexSeed = _startIndexSeed;
            while (oldIndexSeed == _startIndexSeed)
            {
                _startIndexSeed = _rnd.Next(int.MaxValue);
            }
        }

        /// <summary>
        /// Encodes the given index as a four-character string representing the bytes of the number.
        /// </summary>
        private static string EncodeIndex(int startIndex)
        {
            // Appends the start index as the last part of the string after XOR-ing it with _startIndexSeed.
            var strIndex = new string(Array.ConvertAll(BitConverter.GetBytes(startIndex + _startIndexSeed), b => (char)b));
            return strIndex;
        }

        /// <summary>
        /// Returns the int value corresponding to the string passed as parameter (generated by <see cref="EncodeIndex(int)"/>).
        /// </summary>
        /// <param name="strIndex">String representation of the byte array composing the number; must be exactly 4 characters long.</param>
        private static int DecodeIndex(string strIndex)
        {
            if (string.IsNullOrWhiteSpace(strIndex) || strIndex.Length != 4)
            {
                throw new ArgumentException($"{nameof(strIndex)} must be exactly 4 characters long.");
            }
            var index =  BitConverter.ToInt32(Array.ConvertAll(strIndex.ToCharArray(), c => (byte)c), 0) - _startIndexSeed;
            return index;
        }

#if DEBUG

        /// <inheritdoc cref="EncodeIndex(int)"/>
        /// <remarks>For use in tests only.</remarks>
        public static string TestEncodeIndex(int startIndex) => EncodeIndex(startIndex);

        /// <inheritdoc cref="DecodeIndex(string)"/>
        /// <remarks>For use in tests only.</remarks>
        public static int TestDecodeIndex(string strIndex) => DecodeIndex(strIndex);


#endif

    #endregion
    }
}
